---
name: Maven

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      security-events: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Register problem matchers
      run: echo "::add-matcher::.github/matchers.json"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java-kotlin
        queries: security-extended,security-and-quality

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven

    - name: Get AWS credentials
      id: get_aws_credentials
      continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::771971951923:role/keycloak-cas-artifact-upload
        audience: sts.amazonaws.com
        role-duration-seconds: 900

    - name: Build with Maven
      run: mvn -B clean com.spotify.fmt:fmt-maven-plugin:check package ${{ steps.get_aws_credentials.outcome == 'success' && 'deploy' || '' }}

    - name: Upload JAR to GitHub
      uses: actions/upload-artifact@v4
      with:
        path: target/keycloak-cas-services-*-SNAPSHOT.jar
        if-no-files-found: error
        compression-level: 0

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:java-kotlin"

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
      continue-on-error: true
